###

GET https://gstsandbox.charteredinfo.com/taxpayerapi/dec/v1.0/authenticate?action=OTPREQUEST&aspid=1720553323&password=Reithick@1&gstin=33AANCS2882A1ZG&username=TN_NT2.2265

###

GET https://gstapi.charteredinfo.com/commonapi/v1.1/search?aspid=1720553323&password=Reithick@1&Action=TP&Gstin=33AKMPK5944M1ZN&SearchGstin=33AKMPK5944M1ZN


###

GET https://gstapi.charteredinfo.com/commonapi/v1.0/returns?aspid=1720553323&password=Reithick@1&Action=RETTRACK&Gstin=33AKMPK5944M1ZN&fy=2022-23

