@apiUrl = http://localhost:8000
# @apiUrl = https://silversoft.business/api


###

GET {{apiUrl}}/credential/

###

POST {{apiUrl}}/credential/
Content-Type: application/json

{
    "email" : "1",
    "credential_type" : "GST",
    "user_id" : "reithickcorp",
    "password" : "qwerty99",
    "registered_mobile": "86681245358",
    "registered_email": "ashsgh@gmail.com"
}

###

POST {{apiUrl}}/credential/all/
Content-Type: application/json

{
    "email" : "1"
}


###
PUT {{apiUrl}}/credential/63c73eaa0b8f5ffe83578cba
Content-Type: application/json

{
    "email" : "reithick@iitk.ac.in",
    "credential_type" : "GST",
    "user_id" : "reithickcorp",
    "password" : "123456789",
    "PAN": "AEFDW4231L",
    "registered_mobile": "8668124118",
    "registered_email": "naksiitk@gmail.com"
}

###

DELETE {{apiUrl}}/credential/6415637e7323c41a89b6ba8d




@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJlaXRoaWNrQGdtYWlsLmNvbSIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE2NzkxMjA3Njh9.ESSc6EMLUtwjgz6T9xk5jEwWgNWaeN2N_cVI03oI6i8

###

POST {{apiUrl}}/credential/add_new_credential/
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
    "email" : "reithick@gmail.com",
    "credential_type" : "GST",
    "user_id" : "reithickcorp",
    "password" : "123456789",
    "PANorGSTIN": "33AKMPK5944M1ZN",
    "registered_mobile": "8668124118",
    "registered_email": "naksiitk@gmail.com"
}

###

GET {{apiUrl}}/credential/auditor/all/purpose/GST/
Authorization: Bearer {{JWT}}

###

GET {{apiUrl}}/credential/client/all/
Authorization: Bearer {{JWT}}

###

POST {{apiUrl}}/credential/delete/6415637e7323c41a89b6ba8d
Content-Type: application/json
Authorization: Bearer {{JWT}}
