@apiUrl = http://localhost:8000
# @apiUrl = https://silversoft.business/api

@JWT = 

GET {{apiUrl}}/planets/ HTTP/1.1


GET {{apiUrl}}/credential/

###

POST {{apiUrl}}/credential/
Content-Type: application/json

{
    "email" : "1",
    "credential_type" : "GST",
    "user_id" : "reithickcorp",
    "password" : "qwerty99",
    "registered_mobile": "86681245358",
    "registered_email": "ashsgh@gmail.com"
}

###

POST {{apiUrl}}/credential/all/
Content-Type: application/json

{
    "email" : "1"
}


###
PUT {{apiUrl}}/credential/63c73eaa0b8f5ffe83578cba
Content-Type: application/json

{
    "email" : "reithick@iitk.ac.in",
    "credential_type" : "GST",
    "user_id" : "reithickcorp",
    "password" : "123456789",
    "PAN": "AEFDW4231L",
    "registered_mobile": "8668124118",
    "registered_email": "naksiitk@gmail.com"
}

###

DELETE {{apiUrl}}/credential/63cefaa769d556a624bd643c


###

POST {{apiUrl}}/credential/add_new_credential/
Content-Type: application/json
{
    "email" : "reithick@iitk.ac.in",
    "credential_type" : "GST",
    "user_id" : "reithickcorp",
    "password" : "123456789",
    "PAN/GSTIN": "AEFDW4231L",
    "registered_mobile": "8668124118",
    "registered_email": "naksiitk@gmail.com"
}

###

GET {{apiUrl}}/credential/auditor/all/purpose/{{:id}} { "GST"/"ITR"/"others"}

###

GET {{apiUrl}}/credential/client/all/

###

DELETE {{apiUrl}}/credential/delete/{userid}
