@apiUrl = http://localhost:8000
# @apiUrl = https://silversoft.business/api

@JWT = 

GET {{apiUrl}}/doc/

###

GET {{apiUrl}}/doc/client_list/ITR

###

###

PUT http://localhost:8000/doc/client_summary/seen/6403338e88883611f50372b1
###

GET http://localhost:8000/user/client_doc_summary
GET {{apiUrl}}/user/client_doc_summary

###
POST {{apiUrl}}/doc/
Content-Type: application/json

{"purpose":"TDS","comments":"123","files_uploaded":"123","email":"1","uploadedat":"26/01/2023","fy":"2022-2021","month_quarter":"Q2","fy_month_quarter":"2022-2021 ;Q2"}


###

POST {{apiUrl}}/doc/purpose
Content-Type: application/json

{
    "purpose" : "GST", 
    "email" : "1"
}

###

GET {{apiUrl}}/doc/63c7a4788861b69efc9d7d72

###

DELETE {{apiUrl}}/doc/63c7a4788861b69efc9d7d72


###

PUT {{apiUrl}}/doc/update/63d1a29dd0585e309fc629fc
Content-Type: application/json
{
"filename":"123",
"purpose":"TDS",
"comments":"123",
"files_uploaded":"123",
"email":"1",
"uploadedat":"28/01/2023",
"fy":"2022-2021",
"month_quarter":"Q2",
"fy_month_quarter": "2021-2022; Q1"
}

### DELETE ALL

DELETE {{apiUrl}}/doc


###

PUT {{apiUrl}}/doc/lock/63d1a239d0585e309fc629f4
Content-Type: application/json

{
    "lock" : "true"
}

###

POST {{apiUrl}}/asked_files/asked_files/
Content-Type: application/json

{"filename":"123","purpose":"ITR","comments":"Provide the Bank Statement","email":"1","fy":"2022-2021","month_quarter":""}

###

GET http://localhost:8000/asked_files/asked_files
