GET http://localhost:8000/user
###

GET http://54.90.42.79:80/api/otps

###

GET http://localhost:8000/user/63bad7eb0f73c53301b11d6v

###

POST http://54.90.42.79:80/api/user
Content-Type: application/json

{
    "email": "arasuaudit@gmail.com",
    "password": "qwerty99",
    "mobile": "9443245889",
    "user_name": "Anbarasu",
    "user_type": "auditor",
    "PAN": "AKMPK5944M1"
}

###

POST http://localhost:8000/user/login
Content-Type: application/json

{
    "email": "1",
    "password": "1"
}

###

DELETE http://localhost:8000/user/63cbf908dfe99cb81dbf3e87


###
POST http://54.90.42.79:3056/user/generate_otp
Content-Type: application/json

{
    "email": "2"
}

###

POST http://localhost:8000/user/signup
Content-Type: application/json

{
    "email": "2",
    "password": "2",
    "mobile": "9887241556",
    "user_name": "reithick",
    "user_type": "client",
    "PAN": "MOPJD4592D",
    "OTP": "cbHDT"
}