# @apiUrl = http://localhost:8000
@apiUrl = https://silversoft.business/api

@JWT = 

GET {{apiUrl}}/user

###

GET {{apiUrl}}/otps

###

GET {{apiUrl}}/user/63bad7eb0f73c53301b11d6v

###

POST {{apiUrl}}/user
Content-Type: application/json

{
    "email": "arasuaudit@gmail.com",
    "password": "qwerty99",
    "mobile": "9443245889",
    "user_name": "Anbarasu",
    "user_type": "auditor",
    "PAN": "AKMPK5944M1"
}

###

POST {{apiUrl}}/user/login
Content-Type: application/json

{
    "email": "1",
    "password": "1"
}

###
POST http://localhost:8000/user/verified/check
Content-Type: application/json

{
    "email": "anbarasuparamasivam@gmail.com",
    "verified": "false"
}
###

DELETE {{apiUrl}}/user/63cbf908dfe99cb81dbf3e87

###

DELETE http://localhost:8000/user/delete_client_doc_summary/delete

###

DELETE http://localhost:8000/user/email/anbarasuparamasivam@gmail.com

###
POST {{apiUrl}}/user/generate_otp
Content-Type: application/json

{
    "email": "2"
}

###

POST {{apiUrl}}/user/signup
Content-Type: application/json

{
    "email": "2",
    "password": "2",
    "mobile": "9887241556",
    "user_name": "reithick",
    "user_type": "client",
    "PAN": "MOPJD4592D",
    "OTP": "cbHDT"
}

###

GET {{apiUrl}}/user/onboarding/reithick@gmail.com
